version: "2"

linters:
  enable:
    - copyloopvar
    - dogsled
    - gocritic
    - gocyclo
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unused
  default: none
  settings:
    revive:
      rules:
        - name: exported
          disabled: true
